<?php /** @noinspection PhpUnused */

namespace betsuno\paypal\api;

use PayPal\Api\Links;
use PayPal\Common\PayPalResourceModel;
use PayPal\Rest\ApiContext;
use PayPal\Transport\PayPalRestCall;
use PayPal\Validation\ArgumentValidator;

/**
 * Class CatalogProduct
 * @package betsuno\paypal\api
 * @property string $id
 * @property string $name
 * @property string $description
 * @property string $type
 * @property string $category
 * @property string $image_url
 * @property string $home_url
 * @property string $created_at
 * @property string $updated_at
 * @property Links[] $links
 */
class CatalogProduct extends PayPalResourceModel
{
	const TYPE_PHYSICAL = 'PHYSICAL'; // Physical goods
	const TYPE_DIGITAL = 'DIGITAL'; // Digital goods
	const TYPE_SERVICE = 'SERVICE'; // Product representing a service. Example: Tech Support

	const CATEGORY_AC_REFRIGERATION_REPAIR = 'AC_REFRIGERATION_REPAIR'; // A/C, Refrigeration Repair
	const CATEGORY_ACADEMIC_SOFTWARE = 'ACADEMIC_SOFTWARE'; // Academic Software
	const CATEGORY_ACCESSORIES = 'ACCESSORIES'; // Accessories
	const CATEGORY_ACCOUNTING = 'ACCOUNTING'; // Accounting
	const CATEGORY_ADULT = 'ADULT'; // Adult
	const CATEGORY_ADVERTISING = 'ADVERTISING'; // Advertising
	const CATEGORY_AFFILIATED_AUTO_RENTAL = 'AFFILIATED_AUTO_RENTAL'; // Affiliated Auto Rental
	const CATEGORY_AGENCIES = 'AGENCIES'; // Agencies
	const CATEGORY_AGGREGATORS = 'AGGREGATORS'; // Aggregators
	const CATEGORY_AGRICULTURAL_COOPERATIVE_FOR_MAIL_ORDER = 'AGRICULTURAL_COOPERATIVE_FOR_MAIL_ORDER'; // Agricultural Cooperative for Mail Order
	const CATEGORY_AIR_CARRIERS_AIRLINES = 'AIR_CARRIERS_AIRLINES'; // Air Carriers, Airlines
	const CATEGORY_AIRLINES = 'AIRLINES'; // Airlines
	const CATEGORY_AIRPORTS_FLYING_FIELDS = 'AIRPORTS_FLYING_FIELDS'; // Airports, Flying Fields
	const CATEGORY_ALCOHOLIC_BEVERAGES = 'ALCOHOLIC_BEVERAGES'; // Alcoholic Beverages
	const CATEGORY_AMUSEMENT_PARKS_CARNIVALS = 'AMUSEMENT_PARKS_CARNIVALS'; // Amusement Parks/Carnivals
	const CATEGORY_ANIMATION = 'ANIMATION'; // Animation
	const CATEGORY_ANTIQUES = 'ANTIQUES'; // Antiques
	const CATEGORY_APPLIANCES = 'APPLIANCES'; // Appliances
	const CATEGORY_AQUARIAMS_SEAQUARIUMS_DOLPHINARIUMS = 'AQUARIAMS_SEAQUARIUMS_DOLPHINARIUMS'; // Aquariams Seaquariums Dolphinariums
	const CATEGORY_ARCHITECTURAL_ENGINEERING_AND_SURVEYING_SERVICES = 'ARCHITECTURAL_ENGINEERING_AND_SURVEYING_SERVICES'; // Architectural,Engineering,And Surveying Services
	const CATEGORY_ART_AND_CRAFT_SUPPLIES = 'ART_AND_CRAFT_SUPPLIES'; // Art & Craft Supplies
	const CATEGORY_ART_DEALERS_AND_GALLERIES = 'ART_DEALERS_AND_GALLERIES'; // Art dealers and galleries
	const CATEGORY_ARTIFACTS_GRAVE_RELATED_AND_NATIVE_AMERICAN_CRAFTS = 'ARTIFACTS_GRAVE_RELATED_AND_NATIVE_AMERICAN_CRAFTS'; // Artifacts, Grave related, and Native American Crafts
	const CATEGORY_ARTS_AND_CRAFTS = 'ARTS_AND_CRAFTS'; // Arts and crafts
	const CATEGORY_ARTS_CRAFTS_AND_COLLECTIBLES = 'ARTS_CRAFTS_AND_COLLECTIBLES'; // Arts, crafts, and collectibles
	const CATEGORY_AUDIO_BOOKS = 'AUDIO_BOOKS'; // Audio books
	const CATEGORY_AUTO_ASSOCIATIONS_CLUBS = 'AUTO_ASSOCIATIONS_CLUBS'; // Auto Associations/Clubs
	const CATEGORY_AUTO_DEALER_USED_ONLY = 'AUTO_DEALER_USED_ONLY'; // Auto dealer - used only
	const CATEGORY_AUTO_RENTALS = 'AUTO_RENTALS'; // Auto Rentals
	const CATEGORY_AUTO_SERVICE = 'AUTO_SERVICE'; // Auto service
	const CATEGORY_AUTOMATED_FUEL_DISPENSERS = 'AUTOMATED_FUEL_DISPENSERS'; // Automated Fuel Dispensers
	const CATEGORY_AUTOMOBILE_ASSOCIATIONS = 'AUTOMOBILE_ASSOCIATIONS'; // Automobile Associations
	const CATEGORY_AUTOMOTIVE = 'AUTOMOTIVE'; // Automotive
	const CATEGORY_AUTOMOTIVE_REPAIR_SHOPS_NON_DEALER = 'AUTOMOTIVE_REPAIR_SHOPS_NON_DEALER'; // Automotive Repair Shops - Non-Dealer
	const CATEGORY_AUTOMOTIVE_TOP_AND_BODY_SHOPS = 'AUTOMOTIVE_TOP_AND_BODY_SHOPS'; // Automotive Top And Body Shops
	const CATEGORY_AVIATION = 'AVIATION'; // Aviation
	const CATEGORY_BABIES_CLOTHING_AND_SUPPLIES = 'BABIES_CLOTHING_AND_SUPPLIES'; // Babies Clothing & Supplies
	const CATEGORY_BABY = 'BABY'; // Baby
	const CATEGORY_BANDS_ORCHESTRAS_ENTERTAINERS = 'BANDS_ORCHESTRAS_ENTERTAINERS'; // Bands,Orchestras,Entertainers
	const CATEGORY_BARBIES = 'BARBIES'; // Barbies
	const CATEGORY_BATH_AND_BODY = 'BATH_AND_BODY'; // Bath and body
	const CATEGORY_BATTERIES = 'BATTERIES'; // Batteries
	const CATEGORY_BEAN_BABIES = 'BEAN_BABIES'; // Bean Babies
	const CATEGORY_BEAUTY = 'BEAUTY'; // Beauty
	const CATEGORY_BEAUTY_AND_FRAGRANCES = 'BEAUTY_AND_FRAGRANCES'; // Beauty and fragrances
	const CATEGORY_BED_AND_BATH = 'BED_AND_BATH'; // Bed & Bath
	const CATEGORY_BICYCLE_SHOPS_SALES_AND_SERVICE = 'BICYCLE_SHOPS_SALES_AND_SERVICE'; // Bicycle Shops-Sales And Service
	const CATEGORY_BICYCLES_AND_ACCESSORIES = 'BICYCLES_AND_ACCESSORIES'; // Bicycles & Accessories
	const CATEGORY_BILLIARD_POOL_ESTABLISHMENTS = 'BILLIARD_POOL_ESTABLISHMENTS'; // Billiard/Pool Establishments
	const CATEGORY_BOAT_DEALERS = 'BOAT_DEALERS'; // Boat Dealers
	const CATEGORY_BOAT_RENTALS_AND_LEASING = 'BOAT_RENTALS_AND_LEASING'; // Boat Rentals And Leasing
	const CATEGORY_BOATING_SAILING_AND_ACCESSORIES = 'BOATING_SAILING_AND_ACCESSORIES'; // Boating, sailing and accessories
	const CATEGORY_BOOKS = 'BOOKS'; // Books
	const CATEGORY_BOOKS_AND_MAGAZINES = 'BOOKS_AND_MAGAZINES'; // Books and magazines
	const CATEGORY_BOOKS_MANUSCRIPTS = 'BOOKS_MANUSCRIPTS'; // Books, Manuscripts
	const CATEGORY_BOOKS_PERIODICALS_AND_NEWSPAPERS = 'BOOKS_PERIODICALS_AND_NEWSPAPERS'; // Books, Periodicals And Newspapers
	const CATEGORY_BOWLING_ALLEYS = 'BOWLING_ALLEYS'; // Bowling Alleys
	const CATEGORY_BULLETIN_BOARD = 'BULLETIN_BOARD'; // Bulletin board
	const CATEGORY_BUS_LINE = 'BUS_LINE'; // Bus line
	const CATEGORY_BUS_LINES_CHARTERS_TOUR_BUSES = 'BUS_LINES_CHARTERS_TOUR_BUSES'; // Bus Lines,Charters,Tour Buses
	const CATEGORY_BUSINESS = 'BUSINESS'; // Business
	const CATEGORY_BUSINESS_AND_SECRETARIAL_SCHOOLS = 'BUSINESS_AND_SECRETARIAL_SCHOOLS'; // Business and secretarial schools
	const CATEGORY_BUYING_AND_SHOPPING_SERVICES_AND_CLUBS = 'BUYING_AND_SHOPPING_SERVICES_AND_CLUBS'; // Buying And Shopping Services And Clubs
	const CATEGORY_CABLE_SATELLITE_AND_OTHER_PAY_TELEVISION_AND_RADIO_SERVICES = 'CABLE_SATELLITE_AND_OTHER_PAY_TELEVISION_AND_RADIO_SERVICES'; // Cable,Satellite,And Other Pay Television And Radio Services
	const CATEGORY_CABLE_SATELLITE_AND_OTHER_PAY_TV_AND_RADIO = 'CABLE_SATELLITE_AND_OTHER_PAY_TV_AND_RADIO'; // Cable, satellite, and other pay TV and radio
	const CATEGORY_CAMERA_AND_PHOTOGRAPHIC_SUPPLIES = 'CAMERA_AND_PHOTOGRAPHIC_SUPPLIES'; // Camera and photographic supplies
	const CATEGORY_CAMERAS = 'CAMERAS'; // Cameras
	const CATEGORY_CAMERAS_AND_PHOTOGRAPHY = 'CAMERAS_AND_PHOTOGRAPHY'; // Cameras & Photography
	const CATEGORY_CAMPER_RECREATIONAL_AND_UTILITY_TRAILER_DEALERS = 'CAMPER_RECREATIONAL_AND_UTILITY_TRAILER_DEALERS'; // Camper,Recreational And Utility Trailer Dealers
	const CATEGORY_CAMPING_AND_OUTDOORS = 'CAMPING_AND_OUTDOORS'; // Camping and outdoors
	const CATEGORY_CAMPING_AND_SURVIVAL = 'CAMPING_AND_SURVIVAL'; // Camping & Survival
	const CATEGORY_CAR_AND_TRUCK_DEALERS = 'CAR_AND_TRUCK_DEALERS'; // Car And Truck Dealers
	const CATEGORY_CAR_AND_TRUCK_DEALERS_USED_ONLY = 'CAR_AND_TRUCK_DEALERS_USED_ONLY'; // Car And Truck Dealers - Used Only
	const CATEGORY_CAR_AUDIO_AND_ELECTRONICS = 'CAR_AUDIO_AND_ELECTRONICS'; // Car Audio & Electronics
	const CATEGORY_CAR_RENTAL_AGENCY = 'CAR_RENTAL_AGENCY'; // Car rental agency
	const CATEGORY_CATALOG_MERCHANT = 'CATALOG_MERCHANT'; // Catalog Merchant
	const CATEGORY_CATALOG_RETAIL_MERCHANT = 'CATALOG_RETAIL_MERCHANT'; // Catalog/Retail Merchant
	const CATEGORY_CATERING_SERVICES = 'CATERING_SERVICES'; // Catering services
	const CATEGORY_CHARITY = 'CHARITY'; // Charity
	const CATEGORY_CHECK_CASHIER = 'CHECK_CASHIER'; // Check Cashier
	const CATEGORY_CHILD_CARE_SERVICES = 'CHILD_CARE_SERVICES'; // Child Care Services
	const CATEGORY_CHILDREN_BOOKS = 'CHILDREN_BOOKS'; // Children Books
	const CATEGORY_CHIROPODISTS_PODIATRISTS = 'CHIROPODISTS_PODIATRISTS'; // Chiropodists/Podiatrists
	const CATEGORY_CHIROPRACTORS = 'CHIROPRACTORS'; // Chiropractors
	const CATEGORY_CIGAR_STORES_AND_STANDS = 'CIGAR_STORES_AND_STANDS'; // Cigar Stores And Stands
	const CATEGORY_CIVIC_SOCIAL_FRATERNAL_ASSOCIATIONS = 'CIVIC_SOCIAL_FRATERNAL_ASSOCIATIONS'; // Civic, Social, Fraternal Associations
	const CATEGORY_CIVIL_SOCIAL_FRAT_ASSOCIATIONS = 'CIVIL_SOCIAL_FRAT_ASSOCIATIONS'; // Civil/Social/Frat Associations
	const CATEGORY_CLOTHING = 'CLOTHING'; // Clothing
	const CATEGORY_CLOTHING_ACCESSORIES_AND_SHOES = 'CLOTHING_ACCESSORIES_AND_SHOES'; // Clothing, accessories, and shoes
	const CATEGORY_CLOTHING_RENTAL = 'CLOTHING_RENTAL'; // Clothing Rental
	const CATEGORY_COFFEE_AND_TEA = 'COFFEE_AND_TEA'; // Coffee and tea
	const CATEGORY_COIN_OPERATED_BANKS_AND_CASINOS = 'COIN_OPERATED_BANKS_AND_CASINOS'; // Coin Operated Banks & Casinos
	const CATEGORY_COLLECTIBLES = 'COLLECTIBLES'; // Collectibles
	const CATEGORY_COLLECTION_AGENCY = 'COLLECTION_AGENCY'; // Collection agency
	const CATEGORY_COLLEGES_AND_UNIVERSITIES = 'COLLEGES_AND_UNIVERSITIES'; // Colleges and universities
	const CATEGORY_COMMERCIAL_EQUIPMENT = 'COMMERCIAL_EQUIPMENT'; // Commercial Equipment
	const CATEGORY_COMMERCIAL_FOOTWEAR = 'COMMERCIAL_FOOTWEAR'; // Commercial Footwear
	const CATEGORY_COMMERCIAL_PHOTOGRAPHY = 'COMMERCIAL_PHOTOGRAPHY'; // Commercial photography
	const CATEGORY_COMMERCIAL_PHOTOGRAPHY_ART_AND_GRAPHICS = 'COMMERCIAL_PHOTOGRAPHY_ART_AND_GRAPHICS'; // Commercial photography, art, and graphics
	const CATEGORY_COMMERCIAL_SPORTS_PROFESSIONA = 'COMMERCIAL_SPORTS_PROFESSIONA'; // Commercial Sports/Professiona
	const CATEGORY_COMMODITIES_AND_FUTURES_EXCHANGE = 'COMMODITIES_AND_FUTURES_EXCHANGE'; // Commodities and futures exchange
	const CATEGORY_COMPUTER_AND_DATA_PROCESSING_SERVICES = 'COMPUTER_AND_DATA_PROCESSING_SERVICES'; // Computer and data processing services
	const CATEGORY_COMPUTER_HARDWARE_AND_SOFTWARE = 'COMPUTER_HARDWARE_AND_SOFTWARE'; // Computer Hardware & Software
	const CATEGORY_COMPUTER_MAINTENANCE_REPAIR_AND_SERVICES_NOT_ELSEWHERE_CLAS = 'COMPUTER_MAINTENANCE_REPAIR_AND_SERVICES_NOT_ELSEWHERE_CLAS'; // Computer Maintenance, Repair And Services Not Elsewhere Clas
	const CATEGORY_CONSTRUCTION = 'CONSTRUCTION'; // Construction
	const CATEGORY_CONSTRUCTION_MATERIALS_NOT_ELSEWHERE_CLASSIFIED = 'CONSTRUCTION_MATERIALS_NOT_ELSEWHERE_CLASSIFIED'; // Construction Materials Not Elsewhere Classified
	const CATEGORY_CONSULTING_SERVICES = 'CONSULTING_SERVICES'; // Consulting services
	const CATEGORY_CONSUMER_CREDIT_REPORTING_AGENCIES = 'CONSUMER_CREDIT_REPORTING_AGENCIES'; // Consumer Credit Reporting Agencies
	const CATEGORY_CONVALESCENT_HOMES = 'CONVALESCENT_HOMES'; // Convalescent Homes
	const CATEGORY_COSMETIC_STORES = 'COSMETIC_STORES'; // Cosmetic Stores
	const CATEGORY_COUNSELING_SERVICES_DEBT_MARRIAGE_PERSONAL = 'COUNSELING_SERVICES_DEBT_MARRIAGE_PERSONAL'; // Counseling Services--Debt,Marriage,Personal
	const CATEGORY_COUNTERFEIT_CURRENCY_AND_STAMPS = 'COUNTERFEIT_CURRENCY_AND_STAMPS'; // Counterfeit Currency and Stamps
	const CATEGORY_COUNTERFEIT_ITEMS = 'COUNTERFEIT_ITEMS'; // Counterfeit Items
	const CATEGORY_COUNTRY_CLUBS = 'COUNTRY_CLUBS'; // Country Clubs
	const CATEGORY_COURIER_SERVICES = 'COURIER_SERVICES'; // Courier services
	const CATEGORY_COURIER_SERVICES_AIR_AND_GROUND_AND_FREIGHT_FORWARDERS = 'COURIER_SERVICES_AIR_AND_GROUND_AND_FREIGHT_FORWARDERS'; // Courier Services-Air And Ground,And Freight Forwarders
	const CATEGORY_COURT_COSTS_ALIMNY_CHILD_SUPT = 'COURT_COSTS_ALIMNY_CHILD_SUPT'; // Court Costs/Alimny/Child Supt
	const CATEGORY_COURT_COSTS_INCLUDING_ALIMONY_AND_CHILD_SUPPORT_COURTS_OF_LAW = 'COURT_COSTS_INCLUDING_ALIMONY_AND_CHILD_SUPPORT_COURTS_OF_LAW'; // Court Costs, Including Alimony and Child Support - Courts of Law
	const CATEGORY_CREDIT_CARDS = 'CREDIT_CARDS'; // Credit Cards
	const CATEGORY_CREDIT_UNION = 'CREDIT_UNION'; // Credit union
	const CATEGORY_CULTURE_AND_RELIGION = 'CULTURE_AND_RELIGION'; // Culture & Religion
	const CATEGORY_DAIRY_PRODUCTS_STORES = 'DAIRY_PRODUCTS_STORES'; // Dairy Products Stores
	const CATEGORY_DANCE_HALLS_STUDIOS_AND_SCHOOLS = 'DANCE_HALLS_STUDIOS_AND_SCHOOLS'; // Dance Halls,Studios,And Schools
	const CATEGORY_DECORATIVE = 'DECORATIVE'; // Decorative
	const CATEGORY_DENTAL = 'DENTAL'; // Dental
	const CATEGORY_DENTISTS_AND_ORTHODONTISTS = 'DENTISTS_AND_ORTHODONTISTS'; // Dentists And Orthodontists
	const CATEGORY_DEPARTMENT_STORES = 'DEPARTMENT_STORES'; // Department Stores
	const CATEGORY_DESKTOP_PCS = 'DESKTOP_PCS'; // Desktop PCs
	const CATEGORY_DEVICES = 'DEVICES'; // Devices
	const CATEGORY_DIECAST_TOYS_VEHICLES = 'DIECAST_TOYS_VEHICLES'; // Diecast, Toys Vehicles
	const CATEGORY_DIGITAL_GAMES = 'DIGITAL_GAMES'; // Digital games
	const CATEGORY_DIGITAL_MEDIA_BOOKS_MOVIES_MUSIC = 'DIGITAL_MEDIA_BOOKS_MOVIES_MUSIC'; // Digital media,books,movies,music
	const CATEGORY_DIRECT_MARKETING = 'DIRECT_MARKETING'; // Direct Marketing
	const CATEGORY_DIRECT_MARKETING_CATALOG_MERCHANT = 'DIRECT_MARKETING_CATALOG_MERCHANT'; // Direct Marketing - Catalog Merchant
	const CATEGORY_DIRECT_MARKETING_INBOUND_TELE = 'DIRECT_MARKETING_INBOUND_TELE'; // Direct Marketing - Inbound Tele
	const CATEGORY_DIRECT_MARKETING_OUTBOUND_TELE = 'DIRECT_MARKETING_OUTBOUND_TELE'; // Direct Marketing - Outbound Tele
	const CATEGORY_DIRECT_MARKETING_SUBSCRIPTION = 'DIRECT_MARKETING_SUBSCRIPTION'; // Direct Marketing - Subscription
	const CATEGORY_DISCOUNT_STORES = 'DISCOUNT_STORES'; // Discount Stores
	const CATEGORY_DOOR_TO_DOOR_SALES = 'DOOR_TO_DOOR_SALES'; // Door-To-Door Sales
	const CATEGORY_DRAPERY_WINDOW_COVERING_AND_UPHOLSTERY = 'DRAPERY_WINDOW_COVERING_AND_UPHOLSTERY'; // Drapery, window covering, and upholstery
	const CATEGORY_DRINKING_PLACES = 'DRINKING_PLACES'; // Drinking Places
	const CATEGORY_DRUGSTORE = 'DRUGSTORE'; // Drugstore
	const CATEGORY_DURABLE_GOODS = 'DURABLE_GOODS'; // Durable goods
	const CATEGORY_ECOMMERCE_DEVELOPMENT = 'ECOMMERCE_DEVELOPMENT'; // eCommerce Development
	const CATEGORY_ECOMMERCE_SERVICES = 'ECOMMERCE_SERVICES'; // eCommerce Services
	const CATEGORY_EDUCATIONAL_AND_TEXTBOOKS = 'EDUCATIONAL_AND_TEXTBOOKS'; // Educational and textbooks
	const CATEGORY_ELECTRIC_RAZOR_STORES = 'ELECTRIC_RAZOR_STORES'; // Electric Razor Stores
	const CATEGORY_ELECTRICAL_AND_SMALL_APPLIANCE_REPAIR = 'ELECTRICAL_AND_SMALL_APPLIANCE_REPAIR'; // Electrical and small appliance repair
	const CATEGORY_ELECTRICAL_CONTRACTORS = 'ELECTRICAL_CONTRACTORS'; // Electrical Contractors
	const CATEGORY_ELECTRICAL_PARTS_AND_EQUIPMENT = 'ELECTRICAL_PARTS_AND_EQUIPMENT'; // Electrical Parts and Equipment
	const CATEGORY_ELECTRONIC_CASH = 'ELECTRONIC_CASH'; // Electronic Cash
	const CATEGORY_ELEMENTARY_AND_SECONDARY_SCHOOLS = 'ELEMENTARY_AND_SECONDARY_SCHOOLS'; // Elementary and secondary schools
	const CATEGORY_EMPLOYMENT = 'EMPLOYMENT'; // Employment
	const CATEGORY_ENTERTAINERS = 'ENTERTAINERS'; // Entertainers
	const CATEGORY_ENTERTAINMENT_AND_MEDIA = 'ENTERTAINMENT_AND_MEDIA'; // Entertainment and media
	const CATEGORY_EQUIP_TOOL_FURNITURE_AND_APPLIANCE_RENTAL_AND_LEASING = 'EQUIP_TOOL_FURNITURE_AND_APPLIANCE_RENTAL_AND_LEASING'; // Equip, Tool, Furniture, And Appliance Rental And Leasing
	const CATEGORY_ESCROW = 'ESCROW'; // Escrow
	const CATEGORY_EVENT_AND_WEDDING_PLANNING = 'EVENT_AND_WEDDING_PLANNING'; // Event & Wedding Planning
	const CATEGORY_EXERCISE_AND_FITNESS = 'EXERCISE_AND_FITNESS'; // Exercise and fitness
	const CATEGORY_EXERCISE_EQUIPMENT = 'EXERCISE_EQUIPMENT'; // Exercise Equipment
	const CATEGORY_EXTERMINATING_AND_DISINFECTING_SERVICES = 'EXTERMINATING_AND_DISINFECTING_SERVICES'; // Exterminating and disinfecting services
	const CATEGORY_FABRICS_AND_SEWING = 'FABRICS_AND_SEWING'; // Fabrics & Sewing
	const CATEGORY_FAMILY_CLOTHING_STORES = 'FAMILY_CLOTHING_STORES'; // Family Clothing Stores
	const CATEGORY_FASHION_JEWELRY = 'FASHION_JEWELRY'; // Fashion jewelry
	const CATEGORY_FAST_FOOD_RESTAURANTS = 'FAST_FOOD_RESTAURANTS'; // Fast Food Restaurants
	const CATEGORY_FICTION_AND_NONFICTION = 'FICTION_AND_NONFICTION'; // Fiction and nonfiction
	const CATEGORY_FINANCE_COMPANY = 'FINANCE_COMPANY'; // Finance company
	const CATEGORY_FINANCIAL_AND_INVESTMENT_ADVICE = 'FINANCIAL_AND_INVESTMENT_ADVICE'; // Financial and investment advice
	const CATEGORY_FINANCIAL_INSTITUTIONS_MERCHANDISE_AND_SERVICES = 'FINANCIAL_INSTITUTIONS_MERCHANDISE_AND_SERVICES'; // Financial Institutions - Merchandise And Services
	const CATEGORY_FIREARM_ACCESSORIES = 'FIREARM_ACCESSORIES'; // Firearm accessories
	const CATEGORY_FIREARMS_WEAPONS_AND_KNIVES = 'FIREARMS_WEAPONS_AND_KNIVES'; // Firearms, Weapons and Knives
	const CATEGORY_FIREPLACE_AND_FIREPLACE_SCREENS = 'FIREPLACE_AND_FIREPLACE_SCREENS'; // Fireplace, and fireplace screens
	const CATEGORY_FIREWORKS = 'FIREWORKS'; // Fireworks
	const CATEGORY_FISHING = 'FISHING'; // Fishing
	const CATEGORY_FLORISTS = 'FLORISTS'; // Florists
	const CATEGORY_FLOWERS = 'FLOWERS'; // Flowers
	const CATEGORY_FOOD_DRINK_AND_NUTRITION = 'FOOD_DRINK_AND_NUTRITION'; // Food, Drink & Nutrition
	const CATEGORY_FOOD_PRODUCTS = 'FOOD_PRODUCTS'; // Food Products
	const CATEGORY_FOOD_RETAIL_AND_SERVICE = 'FOOD_RETAIL_AND_SERVICE'; // Food retail and service
	const CATEGORY_FRAGRANCES_AND_PERFUMES = 'FRAGRANCES_AND_PERFUMES'; // Fragrances and perfumes
	const CATEGORY_FREEZER_AND_LOCKER_MEAT_PROVISIONERS = 'FREEZER_AND_LOCKER_MEAT_PROVISIONERS'; // Freezer and Locker Meat Provisioners
	const CATEGORY_FUEL_DEALERS_FUEL_OIL_WOOD_AND_COAL = 'FUEL_DEALERS_FUEL_OIL_WOOD_AND_COAL'; // Fuel Dealers-Fuel Oil, Wood & Coal
	const CATEGORY_FUEL_DEALERS_NON_AUTOMOTIVE = 'FUEL_DEALERS_NON_AUTOMOTIVE'; // Fuel Dealers - Non Automotive
	const CATEGORY_FUNERAL_SERVICES_AND_CREMATORIES = 'FUNERAL_SERVICES_AND_CREMATORIES'; // Funeral Services & Crematories
	const CATEGORY_FURNISHING_AND_DECORATING = 'FURNISHING_AND_DECORATING'; // Furnishing & Decorating
	const CATEGORY_FURNITURE = 'FURNITURE'; // Furniture
	const CATEGORY_FURRIERS_AND_FUR_SHOPS = 'FURRIERS_AND_FUR_SHOPS'; // Furriers and Fur Shops
	const CATEGORY_GADGETS_AND_OTHER_ELECTRONICS = 'GADGETS_AND_OTHER_ELECTRONICS'; // Gadgets & other electronics
	const CATEGORY_GAMBLING = 'GAMBLING'; // Gambling
	const CATEGORY_GAME_SOFTWARE = 'GAME_SOFTWARE'; // Game Software
	const CATEGORY_GAMES = 'GAMES'; // Games
	const CATEGORY_GARDEN_SUPPLIES = 'GARDEN_SUPPLIES'; // Garden supplies
	const CATEGORY_GENERAL = 'GENERAL'; // General
	const CATEGORY_GENERAL_CONTRACTORS = 'GENERAL_CONTRACTORS'; // General contractors
	const CATEGORY_GENERAL_GOVERNMENT = 'GENERAL_GOVERNMENT'; // General - Government
	const CATEGORY_GENERAL_SOFTWARE = 'GENERAL_SOFTWARE'; // General - Software
	const CATEGORY_GENERAL_TELECOM = 'GENERAL_TELECOM'; // General - Telecom
	const CATEGORY_GIFTS_AND_FLOWERS = 'GIFTS_AND_FLOWERS'; // Gifts and flowers
	const CATEGORY_GLASS_PAINT_AND_WALLPAPER_STORES = 'GLASS_PAINT_AND_WALLPAPER_STORES'; // Glass,Paint,And Wallpaper Stores
	const CATEGORY_GLASSWARE_CRYSTAL_STORES = 'GLASSWARE_CRYSTAL_STORES'; // Glassware, Crystal Stores
	const CATEGORY_GOVERNMENT = 'GOVERNMENT'; // Government
	const CATEGORY_GOVERNMENT_IDS_AND_LICENSES = 'GOVERNMENT_IDS_AND_LICENSES'; // Government IDs and Licenses
	const CATEGORY_GOVERNMENT_LICENSED_ON_LINE_CASINOS_ON_LINE_GAMBLING = 'GOVERNMENT_LICENSED_ON_LINE_CASINOS_ON_LINE_GAMBLING'; // Government Licensed On-Line Casinos - On-Line Gambling
	const CATEGORY_GOVERNMENT_OWNED_LOTTERIES = 'GOVERNMENT_OWNED_LOTTERIES'; // Government-Owned Lotteries
	const CATEGORY_GOVERNMENT_SERVICES = 'GOVERNMENT_SERVICES'; // Government services
	const CATEGORY_GRAPHIC_AND_COMMERCIAL_DESIGN = 'GRAPHIC_AND_COMMERCIAL_DESIGN'; // Graphic & Commercial Design
	const CATEGORY_GREETING_CARDS = 'GREETING_CARDS'; // Greeting Cards
	const CATEGORY_GROCERY_STORES_AND_SUPERMARKETS = 'GROCERY_STORES_AND_SUPERMARKETS'; // Grocery Stores & Supermarkets
	const CATEGORY_HARDWARE_AND_TOOLS = 'HARDWARE_AND_TOOLS'; // Hardware & Tools
	const CATEGORY_HARDWARE_EQUIPMENT_AND_SUPPLIES = 'HARDWARE_EQUIPMENT_AND_SUPPLIES'; // Hardware, Equipment, and Supplies
	const CATEGORY_HAZARDOUS_RESTRICTED_AND_PERISHABLE_ITEMS = 'HAZARDOUS_RESTRICTED_AND_PERISHABLE_ITEMS'; // Hazardous, Restricted and Perishable Items
	const CATEGORY_HEALTH_AND_BEAUTY_SPAS = 'HEALTH_AND_BEAUTY_SPAS'; // Health and beauty spas
	const CATEGORY_HEALTH_AND_NUTRITION = 'HEALTH_AND_NUTRITION'; // Health & Nutrition
	const CATEGORY_HEALTH_AND_PERSONAL_CARE = 'HEALTH_AND_PERSONAL_CARE'; // Health and personal care
	const CATEGORY_HEARING_AIDS_SALES_AND_SUPPLIES = 'HEARING_AIDS_SALES_AND_SUPPLIES'; // Hearing Aids Sales and Supplies
	const CATEGORY_HEATING_PLUMBING_AC = 'HEATING_PLUMBING_AC'; // Heating, Plumbing, AC
	const CATEGORY_HIGH_RISK_MERCHANT = 'HIGH_RISK_MERCHANT'; // High Risk Merchant
	const CATEGORY_HIRING_SERVICES = 'HIRING_SERVICES'; // Hiring services
	const CATEGORY_HOBBIES_TOYS_AND_GAMES = 'HOBBIES_TOYS_AND_GAMES'; // Hobbies, Toys & Games
	const CATEGORY_HOME_AND_GARDEN = 'HOME_AND_GARDEN'; // Home and garden
	const CATEGORY_HOME_AUDIO = 'HOME_AUDIO'; // Home Audio
	const CATEGORY_HOME_DECOR = 'HOME_DECOR'; // Home decor
	const CATEGORY_HOME_ELECTRONICS = 'HOME_ELECTRONICS'; // Home Electronics
	const CATEGORY_HOSPITALS = 'HOSPITALS'; // Hospitals
	const CATEGORY_HOTELS_MOTELS_INNS_RESORTS = 'HOTELS_MOTELS_INNS_RESORTS'; // Hotels/Motels/Inns/Resorts
	const CATEGORY_HOUSEWARES = 'HOUSEWARES'; // Housewares
	const CATEGORY_HUMAN_PARTS_AND_REMAINS = 'HUMAN_PARTS_AND_REMAINS'; // Human Parts and Remains
	const CATEGORY_HUMOROUS_GIFTS_AND_NOVELTIES = 'HUMOROUS_GIFTS_AND_NOVELTIES'; // Humorous Gifts & Novelties
	const CATEGORY_HUNTING = 'HUNTING'; // Hunting
	const CATEGORY_IDS_LICENSES_AND_PASSPORTS = 'IDS_LICENSES_AND_PASSPORTS'; // IDs, licenses, and passports
	const CATEGORY_ILLEGAL_DRUGS_AND_PARAPHERNALIA = 'ILLEGAL_DRUGS_AND_PARAPHERNALIA'; // Illegal Drugs & Paraphernalia
	const CATEGORY_INDUSTRIAL = 'INDUSTRIAL'; // Industrial
	const CATEGORY_INDUSTRIAL_AND_MANUFACTURING_SUPPLIES = 'INDUSTRIAL_AND_MANUFACTURING_SUPPLIES'; // Industrial and manufacturing supplies
	const CATEGORY_INSURANCE_AUTO_AND_HOME = 'INSURANCE_AUTO_AND_HOME'; // Insurance - auto and home
	const CATEGORY_INSURANCE_DIRECT = 'INSURANCE_DIRECT'; // Insurance - Direct
	const CATEGORY_INSURANCE_LIFE_AND_ANNUITY = 'INSURANCE_LIFE_AND_ANNUITY'; // Insurance - life and annuity
	const CATEGORY_INSURANCE_SALES_UNDERWRITING = 'INSURANCE_SALES_UNDERWRITING'; // Insurance Sales/Underwriting
	const CATEGORY_INSURANCE_UNDERWRITING_PREMIUMS = 'INSURANCE_UNDERWRITING_PREMIUMS'; // Insurance Underwriting, Premiums
	const CATEGORY_INTERNET_AND_NETWORK_SERVICES = 'INTERNET_AND_NETWORK_SERVICES'; // Internet & Network Services
	const CATEGORY_INTRA_COMPANY_PURCHASES = 'INTRA_COMPANY_PURCHASES'; // Intra-Company Purchases
	const CATEGORY_LABORATORIES_DENTAL_MEDICAL = 'LABORATORIES_DENTAL_MEDICAL'; // Laboratories-Dental/Medical
	const CATEGORY_LANDSCAPING = 'LANDSCAPING'; // Landscaping
	const CATEGORY_LANDSCAPING_AND_HORTICULTURAL_SERVICES = 'LANDSCAPING_AND_HORTICULTURAL_SERVICES'; // Landscaping And Horticultural Services
	const CATEGORY_LAUNDRY_CLEANING_SERVICES = 'LAUNDRY_CLEANING_SERVICES'; // Laundry, Cleaning Services
	const CATEGORY_LEGAL = 'LEGAL'; // Legal
	const CATEGORY_LEGAL_SERVICES_AND_ATTORNEYS = 'LEGAL_SERVICES_AND_ATTORNEYS'; // Legal services and attorneys
	const CATEGORY_LOCAL_DELIVERY_SERVICE = 'LOCAL_DELIVERY_SERVICE'; // Local delivery service
	const CATEGORY_LOCKSMITH = 'LOCKSMITH'; // Locksmith
	const CATEGORY_LODGING_AND_ACCOMMODATIONS = 'LODGING_AND_ACCOMMODATIONS'; // Lodging and accommodations
	const CATEGORY_LOTTERY_AND_CONTESTS = 'LOTTERY_AND_CONTESTS'; // Lottery and contests
	const CATEGORY_LUGGAGE_AND_LEATHER_GOODS = 'LUGGAGE_AND_LEATHER_GOODS'; // Luggage and leather goods
	const CATEGORY_LUMBER_AND_BUILDING_MATERIALS = 'LUMBER_AND_BUILDING_MATERIALS'; // Lumber & Building Materials
	const CATEGORY_MAGAZINES = 'MAGAZINES'; // Magazines
	const CATEGORY_MAINTENANCE_AND_REPAIR_SERVICES = 'MAINTENANCE_AND_REPAIR_SERVICES'; // Maintenance and repair services
	const CATEGORY_MAKEUP_AND_COSMETICS = 'MAKEUP_AND_COSMETICS'; // Makeup and cosmetics
	const CATEGORY_MANUAL_CASH_DISBURSEMENTS = 'MANUAL_CASH_DISBURSEMENTS'; // Manual Cash Disbursements
	const CATEGORY_MASSAGE_PARLORS = 'MASSAGE_PARLORS'; // Massage Parlors
	const CATEGORY_MEDICAL = 'MEDICAL'; // Medical
	const CATEGORY_MEDICAL_AND_PHARMACEUTICAL = 'MEDICAL_AND_PHARMACEUTICAL'; // Medical & Pharmaceutical
	const CATEGORY_MEDICAL_CARE = 'MEDICAL_CARE'; // Medical care
	const CATEGORY_MEDICAL_EQUIPMENT_AND_SUPPLIES = 'MEDICAL_EQUIPMENT_AND_SUPPLIES'; // Medical equipment and supplies
	const CATEGORY_MEDICAL_SERVICES = 'MEDICAL_SERVICES'; // Medical Services
	const CATEGORY_MEETING_PLANNERS = 'MEETING_PLANNERS'; // Meeting Planners
	const CATEGORY_MEMBERSHIP_CLUBS_AND_ORGANIZATIONS = 'MEMBERSHIP_CLUBS_AND_ORGANIZATIONS'; // Membership clubs and organizations
	const CATEGORY_MEMBERSHIP_COUNTRY_CLUBS_GOLF = 'MEMBERSHIP_COUNTRY_CLUBS_GOLF'; // Membership/Country Clubs/Golf
	const CATEGORY_MEMORABILIA = 'MEMORABILIA'; // Memorabilia
	const CATEGORY_MEN_AND_BOY_CLOTHING_AND_ACCESSORY_STORES = 'MEN_AND_BOY_CLOTHING_AND_ACCESSORY_STORES'; // Men's And Boy's Clothing And Accessory Stores
	const CATEGORY_MEN_CLOTHING = 'MEN_CLOTHING'; // Men's Clothing
	const CATEGORY_MERCHANDISE = 'MERCHANDISE'; // Merchandise
	const CATEGORY_METAPHYSICAL = 'METAPHYSICAL'; // Metaphysical
	const CATEGORY_MILITARIA = 'MILITARIA'; // Militaria
	const CATEGORY_MILITARY_AND_CIVIL_SERVICE_UNIFORMS = 'MILITARY_AND_CIVIL_SERVICE_UNIFORMS'; // Military and civil service uniforms
	const CATEGORY_MISC_AUTOMOTIVE_AIRCRAFT_AND_FARM_EQUIPMENT_DEALERS = 'MISC_AUTOMOTIVE_AIRCRAFT_AND_FARM_EQUIPMENT_DEALERS'; // Misc. Automotive,Aircraft,And Farm Equipment Dealers
	const CATEGORY_MISC_GENERAL_MERCHANDISE = 'MISC_GENERAL_MERCHANDISE'; // Misc. General Merchandise
	const CATEGORY_MISCELLANEOUS_GENERAL_SERVICES = 'MISCELLANEOUS_GENERAL_SERVICES'; // Miscellaneous General Services
	const CATEGORY_MISCELLANEOUS_REPAIR_SHOPS_AND_RELATED_SERVICES = 'MISCELLANEOUS_REPAIR_SHOPS_AND_RELATED_SERVICES'; // Miscellaneous Repair Shops And Related Services
	const CATEGORY_MODEL_KITS = 'MODEL_KITS'; // Model Kits
	const CATEGORY_MONEY_TRANSFER_MEMBER_FINANCIAL_INSTITUTION = 'MONEY_TRANSFER_MEMBER_FINANCIAL_INSTITUTION'; // Money Transfer - Member Financial Institution
	const CATEGORY_MONEY_TRANSFER_MERCHANT = 'MONEY_TRANSFER_MERCHANT'; // Money Transfer--Merchant
	const CATEGORY_MOTION_PICTURE_THEATERS = 'MOTION_PICTURE_THEATERS'; // Motion Picture Theaters
	const CATEGORY_MOTOR_FREIGHT_CARRIERS_AND_TRUCKING = 'MOTOR_FREIGHT_CARRIERS_AND_TRUCKING'; // Motor Freight Carriers & Trucking
	const CATEGORY_MOTOR_HOME_AND_RECREATIONAL_VEHICLE_RENTAL = 'MOTOR_HOME_AND_RECREATIONAL_VEHICLE_RENTAL'; // Motor Home And Recreational Vehicle Rental
	const CATEGORY_MOTOR_HOMES_DEALERS = 'MOTOR_HOMES_DEALERS'; // Motor Homes Dealers
	const CATEGORY_MOTOR_VEHICLE_SUPPLIES_AND_NEW_PARTS = 'MOTOR_VEHICLE_SUPPLIES_AND_NEW_PARTS'; // Motor Vehicle Supplies and New Parts
	const CATEGORY_MOTORCYCLE_DEALERS = 'MOTORCYCLE_DEALERS'; // Motorcycle Dealers
	const CATEGORY_MOTORCYCLES = 'MOTORCYCLES'; // Motorcycles
	const CATEGORY_MOVIE = 'MOVIE'; // Movie
	const CATEGORY_MOVIE_TICKETS = 'MOVIE_TICKETS'; // Movie tickets
	const CATEGORY_MOVING_AND_STORAGE = 'MOVING_AND_STORAGE'; // Moving and storage
	const CATEGORY_MULTI_LEVEL_MARKETING = 'MULTI_LEVEL_MARKETING'; // Multi-level marketing
	const CATEGORY_MUSIC_CDS_CASSETTES_AND_ALBUMS = 'MUSIC_CDS_CASSETTES_AND_ALBUMS'; // Music - CDs, cassettes and albums
	const CATEGORY_MUSIC_STORE_INSTRUMENTS_AND_SHEET_MUSIC = 'MUSIC_STORE_INSTRUMENTS_AND_SHEET_MUSIC'; // Music store - instruments and sheet music
	const CATEGORY_NETWORKING = 'NETWORKING'; // Networking
	const CATEGORY_NEW_AGE = 'NEW_AGE'; // New Age
	const CATEGORY_NEW_PARTS_AND_SUPPLIES_MOTOR_VEHICLE = 'NEW_PARTS_AND_SUPPLIES_MOTOR_VEHICLE'; // New parts and supplies - motor vehicle
	const CATEGORY_NEWS_DEALERS_AND_NEWSTANDS = 'NEWS_DEALERS_AND_NEWSTANDS'; // News Dealers and Newstands
	const CATEGORY_NON_DURABLE_GOODS = 'NON_DURABLE_GOODS'; // Non-durable goods
	const CATEGORY_NON_FICTION = 'NON_FICTION'; // Non-Fiction
	const CATEGORY_NON_PROFIT_POLITICAL_AND_RELIGION = 'NON_PROFIT_POLITICAL_AND_RELIGION'; // Non-Profit, Political & Religion
	const CATEGORY_NONPROFIT = 'NONPROFIT'; // Nonprofit
	const CATEGORY_NOVELTIES = 'NOVELTIES'; // Novelties
	const CATEGORY_OEM_SOFTWARE = 'OEM_SOFTWARE'; // Oem Software
	const CATEGORY_OFFICE_SUPPLIES_AND_EQUIPMENT = 'OFFICE_SUPPLIES_AND_EQUIPMENT'; // Office Supplies and Equipment
	const CATEGORY_ONLINE_DATING = 'ONLINE_DATING'; // Online Dating
	const CATEGORY_ONLINE_GAMING = 'ONLINE_GAMING'; // Online gaming
	const CATEGORY_ONLINE_GAMING_CURRENCY = 'ONLINE_GAMING_CURRENCY'; // Online gaming currency
	const CATEGORY_ONLINE_SERVICES = 'ONLINE_SERVICES'; // online services
	const CATEGORY_OOUTBOUND_TELEMARKETING_MERCH = 'OOUTBOUND_TELEMARKETING_MERCH'; // Ooutbound Telemarketing Merch
	const CATEGORY_OPHTHALMOLOGISTS_OPTOMETRIST = 'OPHTHALMOLOGISTS_OPTOMETRIST'; // Ophthalmologists/Optometrist
	const CATEGORY_OPTICIANS_AND_DISPENSING = 'OPTICIANS_AND_DISPENSING'; // Opticians And Dispensing
	const CATEGORY_ORTHOPEDIC_GOODS_PROSTHETICS = 'ORTHOPEDIC_GOODS_PROSTHETICS'; // Orthopedic Goods/Prosthetics
	const CATEGORY_OSTEOPATHS = 'OSTEOPATHS'; // Osteopaths
	const CATEGORY_OTHER = 'OTHER'; // Other
	const CATEGORY_PACKAGE_TOUR_OPERATORS = 'PACKAGE_TOUR_OPERATORS'; // Package Tour Operators
	const CATEGORY_PAINTBALL = 'PAINTBALL'; // Paintball
	const CATEGORY_PAINTS_VARNISHES_AND_SUPPLIES = 'PAINTS_VARNISHES_AND_SUPPLIES'; // Paints, Varnishes, and Supplies
	const CATEGORY_PARKING_LOTS_AND_GARAGES = 'PARKING_LOTS_AND_GARAGES'; // Parking Lots & Garages
	const CATEGORY_PARTS_AND_ACCESSORIES = 'PARTS_AND_ACCESSORIES'; // Parts and accessories
	const CATEGORY_PAWN_SHOPS = 'PAWN_SHOPS'; // Pawn Shops
	const CATEGORY_PAYCHECK_LENDER_OR_CASH_ADVANCE = 'PAYCHECK_LENDER_OR_CASH_ADVANCE'; // Paycheck lender or cash advance
	const CATEGORY_PERIPHERALS = 'PERIPHERALS'; // Peripherals
	const CATEGORY_PERSONALIZED_GIFTS = 'PERSONALIZED_GIFTS'; // Personalized Gifts
	const CATEGORY_PET_SHOPS_PET_FOOD_AND_SUPPLIES = 'PET_SHOPS_PET_FOOD_AND_SUPPLIES'; // Pet shops, pet food, and supplies
	const CATEGORY_PETROLEUM_AND_PETROLEUM_PRODUCTS = 'PETROLEUM_AND_PETROLEUM_PRODUCTS'; // Petroleum and Petroleum Products
	const CATEGORY_PETS_AND_ANIMALS = 'PETS_AND_ANIMALS'; // Pets and animals
	const CATEGORY_PHOTOFINISHING_LABORATORIES_PHOTO_DEVELOPING = 'PHOTOFINISHING_LABORATORIES_PHOTO_DEVELOPING'; // Photofinishing Laboratories,Photo Developing
	const CATEGORY_PHOTOGRAPHIC_STUDIOS_PORTRAITS = 'PHOTOGRAPHIC_STUDIOS_PORTRAITS'; // Photographic studios - portraits
	const CATEGORY_PHOTOGRAPHY = 'PHOTOGRAPHY'; // Photography
	const CATEGORY_PHYSICAL_GOOD = 'PHYSICAL_GOOD'; // Physical Good
	const CATEGORY_PICTURE_VIDEO_PRODUCTION = 'PICTURE_VIDEO_PRODUCTION'; // Picture/Video Production
	const CATEGORY_PIECE_GOODS_NOTIONS_AND_OTHER_DRY_GOODS = 'PIECE_GOODS_NOTIONS_AND_OTHER_DRY_GOODS'; // Piece Goods Notions and Other Dry Goods
	const CATEGORY_PLANTS_AND_SEEDS = 'PLANTS_AND_SEEDS'; // Plants and Seeds
	const CATEGORY_PLUMBING_AND_HEATING_EQUIPMENTS_AND_SUPPLIES = 'PLUMBING_AND_HEATING_EQUIPMENTS_AND_SUPPLIES'; // Plumbing & Heating Equipments & Supplies
	const CATEGORY_POLICE_RELATED_ITEMS = 'POLICE_RELATED_ITEMS'; // Police-Related Items
	const CATEGORY_POLITICAL_ORGANIZATIONS = 'POLITICAL_ORGANIZATIONS'; // Politcal Organizations
	const CATEGORY_POSTAL_SERVICES_GOVERNMENT_ONLY = 'POSTAL_SERVICES_GOVERNMENT_ONLY'; // Postal Services - Government Only
	const CATEGORY_POSTERS = 'POSTERS'; // Posters
	const CATEGORY_PREPAID_AND_STORED_VALUE_CARDS = 'PREPAID_AND_STORED_VALUE_CARDS'; // Prepaid and stored value cards
	const CATEGORY_PRESCRIPTION_DRUGS = 'PRESCRIPTION_DRUGS'; // Prescription Drugs
	const CATEGORY_PROMOTIONAL_ITEMS = 'PROMOTIONAL_ITEMS'; // Promotional Items
	const CATEGORY_PUBLIC_WAREHOUSING_AND_STORAGE = 'PUBLIC_WAREHOUSING_AND_STORAGE'; // Public Warehousing and Storage
	const CATEGORY_PUBLISHING_AND_PRINTING = 'PUBLISHING_AND_PRINTING'; // Publishing and printing
	const CATEGORY_PUBLISHING_SERVICES = 'PUBLISHING_SERVICES'; // Publishing Services
	const CATEGORY_RADAR_DECTORS = 'RADAR_DECTORS'; // Radar Dectors
	const CATEGORY_RADIO_TELEVISION_AND_STEREO_REPAIR = 'RADIO_TELEVISION_AND_STEREO_REPAIR'; // Radio, television, and stereo repair
	const CATEGORY_REAL_ESTATE = 'REAL_ESTATE'; // Real Estate
	const CATEGORY_REAL_ESTATE_AGENT = 'REAL_ESTATE_AGENT'; // Real estate agent
	const CATEGORY_REAL_ESTATE_AGENTS_AND_MANAGERS_RENTALS = 'REAL_ESTATE_AGENTS_AND_MANAGERS_RENTALS'; // Real Estate Agents And Managers - Rentals
	const CATEGORY_RELIGION_AND_SPIRITUALITY_FOR_PROFIT = 'RELIGION_AND_SPIRITUALITY_FOR_PROFIT'; // Religion and spirituality for profit
	const CATEGORY_RELIGIOUS = 'RELIGIOUS'; // Religious
	const CATEGORY_RELIGIOUS_ORGANIZATIONS = 'RELIGIOUS_ORGANIZATIONS'; // Religious Organizations
	const CATEGORY_REMITTANCE = 'REMITTANCE'; // Remittance
	const CATEGORY_RENTAL_PROPERTY_MANAGEMENT = 'RENTAL_PROPERTY_MANAGEMENT'; // Rental property management
	const CATEGORY_RESIDENTIAL = 'RESIDENTIAL'; // Residential
	const CATEGORY_RETAIL = 'RETAIL'; // Retail
	const CATEGORY_RETAIL_FINE_JEWELRY_AND_WATCHES = 'RETAIL_FINE_JEWELRY_AND_WATCHES'; // Retail - fine jewelry and watches
	const CATEGORY_REUPHOLSTERY_AND_FURNITURE_REPAIR = 'REUPHOLSTERY_AND_FURNITURE_REPAIR'; // Reupholstery and furniture repair
	const CATEGORY_RINGS = 'RINGS'; // Rings
	const CATEGORY_ROOFING_SIDING_SHEET_METAL = 'ROOFING_SIDING_SHEET_METAL'; // Roofing/Siding, Sheet Metal
	const CATEGORY_RUGS_AND_CARPETS = 'RUGS_AND_CARPETS'; // Rugs & Carpets
	const CATEGORY_SCHOOLS_AND_COLLEGES = 'SCHOOLS_AND_COLLEGES'; // Schools and Colleges
	const CATEGORY_SCIENCE_FICTION = 'SCIENCE_FICTION'; // Science Fiction
	const CATEGORY_SCRAPBOOKING = 'SCRAPBOOKING'; // Scrapbooking
	const CATEGORY_SCULPTURES = 'SCULPTURES'; // Sculptures
	const CATEGORY_SECURITIES_BROKERS_AND_DEALERS = 'SECURITIES_BROKERS_AND_DEALERS'; // Securities - Brokers And Dealers
	const CATEGORY_SECURITY_AND_SURVEILLANCE = 'SECURITY_AND_SURVEILLANCE'; // Security and surveillance
	const CATEGORY_SECURITY_AND_SURVEILLANCE_EQUIPMENT = 'SECURITY_AND_SURVEILLANCE_EQUIPMENT'; // Security and surveillance equipment
	const CATEGORY_SECURITY_BROKERS_AND_DEALERS = 'SECURITY_BROKERS_AND_DEALERS'; // Security brokers and dealers
	const CATEGORY_SEMINARS = 'SEMINARS'; // Seminars
	const CATEGORY_SERVICE_STATIONS = 'SERVICE_STATIONS'; // Service Stations
	const CATEGORY_SERVICES = 'SERVICES'; // Services
	const CATEGORY_SEWING_NEEDLEWORK_FABRIC_AND_PIECE_GOODS_STORES = 'SEWING_NEEDLEWORK_FABRIC_AND_PIECE_GOODS_STORES'; // Sewing,Needlework,Fabric And Piece Goods Stores
	const CATEGORY_SHIPPING_AND_PACKING = 'SHIPPING_AND_PACKING'; // Shipping & Packaging
	const CATEGORY_SHOE_REPAIR_HAT_CLEANING = 'SHOE_REPAIR_HAT_CLEANING'; // Shoe Repair/Hat Cleaning
	const CATEGORY_SHOE_STORES = 'SHOE_STORES'; // Shoe Stores
	const CATEGORY_SHOES = 'SHOES'; // Shoes
	const CATEGORY_SNOWMOBILE_DEALERS = 'SNOWMOBILE_DEALERS'; // Snowmobile Dealers
	const CATEGORY_SOFTWARE = 'SOFTWARE'; // Software
	const CATEGORY_SPECIALTY_AND_MISC_FOOD_STORES = 'SPECIALTY_AND_MISC_FOOD_STORES'; // Specialty and misc. food stores
	const CATEGORY_SPECIALTY_CLEANING_POLISHING_AND_SANITATION_PREPARATIONS = 'SPECIALTY_CLEANING_POLISHING_AND_SANITATION_PREPARATIONS'; // Specialty Cleaning, Polishing And Sanitation Preparations
	const CATEGORY_SPECIALTY_OR_RARE_PETS = 'SPECIALTY_OR_RARE_PETS'; // Specialty or rare pets
	const CATEGORY_SPORT_GAMES_AND_TOYS = 'SPORT_GAMES_AND_TOYS'; // Sport games and toys
	const CATEGORY_SPORTING_AND_RECREATIONAL_CAMPS = 'SPORTING_AND_RECREATIONAL_CAMPS'; // Sporting And Recreational Camps
	const CATEGORY_SPORTING_GOODS = 'SPORTING_GOODS'; // Sporting Goods
	const CATEGORY_SPORTS_AND_OUTDOORS = 'SPORTS_AND_OUTDOORS'; // Sports and outdoors
	const CATEGORY_SPORTS_AND_RECREATION = 'SPORTS_AND_RECREATION'; // Sports & Recreation
	const CATEGORY_STAMP_AND_COIN = 'STAMP_AND_COIN'; // Stamp and coin
	const CATEGORY_STATIONARY_PRINTING_AND_WRITING_PAPER = 'STATIONARY_PRINTING_AND_WRITING_PAPER'; // Stationary, printing, and writing paper
	const CATEGORY_STENOGRAPHIC_AND_SECRETARIAL_SUPPORT_SERVICES = 'STENOGRAPHIC_AND_SECRETARIAL_SUPPORT_SERVICES'; // Stenographic and secretarial support services
	const CATEGORY_STOCKS_BONDS_SECURITIES_AND_RELATED_CERTIFICATES = 'STOCKS_BONDS_SECURITIES_AND_RELATED_CERTIFICATES'; // Stocks, Bonds, Securities and Related Certificates
	const CATEGORY_STORED_VALUE_CARDS = 'STORED_VALUE_CARDS'; // Stored Value Cards
	const CATEGORY_SUPPLIES = 'SUPPLIES'; // Supplies
	const CATEGORY_SUPPLIES_AND_TOYS = 'SUPPLIES_AND_TOYS'; // Supplies & Toys
	const CATEGORY_SURVEILLANCE_EQUIPMENT = 'SURVEILLANCE_EQUIPMENT'; // Surveillance Equipment
	const CATEGORY_SWIMMING_POOLS_AND_SPAS = 'SWIMMING_POOLS_AND_SPAS'; // Swimming Pools & Spas
	const CATEGORY_SWIMMING_POOLS_SALES_SUPPLIES_SERVICES = 'SWIMMING_POOLS_SALES_SUPPLIES_SERVICES'; // Swimming Pools-Sales,Supplies,Services
	const CATEGORY_TAILORS_AND_ALTERATIONS = 'TAILORS_AND_ALTERATIONS'; // Tailors and alterations
	const CATEGORY_TAX_PAYMENTS = 'TAX_PAYMENTS'; // Tax Payments
	const CATEGORY_TAX_PAYMENTS_GOVERNMENT_AGENCIES = 'TAX_PAYMENTS_GOVERNMENT_AGENCIES'; // Tax Payments - Government Agencies
	const CATEGORY_TAXICABS_AND_LIMOUSINES = 'TAXICABS_AND_LIMOUSINES'; // Taxicabs and limousines
	const CATEGORY_TELECOMMUNICATION_SERVICES = 'TELECOMMUNICATION_SERVICES'; // Telecommunication Services
	const CATEGORY_TELEPHONE_CARDS = 'TELEPHONE_CARDS'; // Telephone Cards
	const CATEGORY_TELEPHONE_EQUIPMENT = 'TELEPHONE_EQUIPMENT'; // Telephone Equipment
	const CATEGORY_TELEPHONE_SERVICES = 'TELEPHONE_SERVICES'; // Telephone Services
	const CATEGORY_THEATER = 'THEATER'; // Theater
	const CATEGORY_TIRE_RETREADING_AND_REPAIR = 'TIRE_RETREADING_AND_REPAIR'; // Tire Retreading and Repair
	const CATEGORY_TOLL_OR_BRIDGE_FEES = 'TOLL_OR_BRIDGE_FEES'; // Toll or Bridge Fees
	const CATEGORY_TOOLS_AND_EQUIPMENT = 'TOOLS_AND_EQUIPMENT'; // Tools and equipment
	const CATEGORY_TOURIST_ATTRACTIONS_AND_EXHIBITS = 'TOURIST_ATTRACTIONS_AND_EXHIBITS'; // Tourist Attractions And Exhibits
	const CATEGORY_TOWING_SERVICE = 'TOWING_SERVICE'; // Towing service
	const CATEGORY_TOYS_AND_GAMES = 'TOYS_AND_GAMES'; // Toys and games
	const CATEGORY_TRADE_AND_VOCATIONAL_SCHOOLS = 'TRADE_AND_VOCATIONAL_SCHOOLS'; // Trade And Vocational Schools
	const CATEGORY_TRADEMARK_INFRINGEMENT = 'TRADEMARK_INFRINGEMENT'; // Trademark Infringement
	const CATEGORY_TRAILER_PARKS_AND_CAMPGROUNDS = 'TRAILER_PARKS_AND_CAMPGROUNDS'; // Trailer Parks And Campgrounds
	const CATEGORY_TRAINING_SERVICES = 'TRAINING_SERVICES'; // Training services
	const CATEGORY_TRANSPORTATION_SERVICES = 'TRANSPORTATION_SERVICES'; // Transportation Services
	const CATEGORY_TRAVEL = 'TRAVEL'; // Travel
	const CATEGORY_TRUCK_AND_UTILITY_TRAILER_RENTALS = 'TRUCK_AND_UTILITY_TRAILER_RENTALS'; // Truck And Utility Trailer Rentals
	const CATEGORY_TRUCK_STOP = 'TRUCK_STOP'; // Truck Stop
	const CATEGORY_TYPESETTING_PLATE_MAKING_AND_RELATED_SERVICES = 'TYPESETTING_PLATE_MAKING_AND_RELATED_SERVICES'; // Typesetting, Plate Making, and Related Services
	const CATEGORY_USED_MERCHANDISE_AND_SECONDHAND_STORES = 'USED_MERCHANDISE_AND_SECONDHAND_STORES'; // Used Merchandise And Secondhand Stores
	const CATEGORY_USED_PARTS_MOTOR_VEHICLE = 'USED_PARTS_MOTOR_VEHICLE'; // Used parts - motor vehicle
	const CATEGORY_UTILITIES = 'UTILITIES'; // Utilities
	const CATEGORY_UTILITIES_ELECTRIC_GAS_WATER_SANITARY = 'UTILITIES_ELECTRIC_GAS_WATER_SANITARY'; // Utilities - Electric,Gas,Water,Sanitary
	const CATEGORY_VARIETY_STORES = 'VARIETY_STORES'; // Variety Stores
	const CATEGORY_VEHICLE_SALES = 'VEHICLE_SALES'; // Vehicle sales
	const CATEGORY_VEHICLE_SERVICE_AND_ACCESSORIES = 'VEHICLE_SERVICE_AND_ACCESSORIES'; // Vehicle service and accessories
	const CATEGORY_VIDEO_EQUIPMENT = 'VIDEO_EQUIPMENT'; // Video Equipment
	const CATEGORY_VIDEO_GAME_ARCADES_ESTABLISH = 'VIDEO_GAME_ARCADES_ESTABLISH'; // Video Game Arcades/Establish
	const CATEGORY_VIDEO_GAMES_AND_SYSTEMS = 'VIDEO_GAMES_AND_SYSTEMS'; // Video Games & Systems
	const CATEGORY_VIDEO_TAPE_RENTAL_STORES = 'VIDEO_TAPE_RENTAL_STORES'; // Video Tape Rental Stores
	const CATEGORY_VINTAGE_AND_COLLECTIBLE_VEHICLES = 'VINTAGE_AND_COLLECTIBLE_VEHICLES'; // Vintage and Collectible Vehicles
	const CATEGORY_VINTAGE_AND_COLLECTIBLES = 'VINTAGE_AND_COLLECTIBLES'; // Vintage and collectibles
	const CATEGORY_VITAMINS_AND_SUPPLEMENTS = 'VITAMINS_AND_SUPPLEMENTS'; // Vitamins & Supplements
	const CATEGORY_VOCATIONAL_AND_TRADE_SCHOOLS = 'VOCATIONAL_AND_TRADE_SCHOOLS'; // Vocational and trade schools
	const CATEGORY_WATCH_CLOCK_AND_JEWELRY_REPAIR = 'WATCH_CLOCK_AND_JEWELRY_REPAIR'; // Watch, clock, and jewelry repair
	const CATEGORY_WEB_HOSTING_AND_DESIGN = 'WEB_HOSTING_AND_DESIGN'; // Web hosting and design
	const CATEGORY_WELDING_REPAIR = 'WELDING_REPAIR'; // Welding Repair
	const CATEGORY_WHOLESALE_CLUBS = 'WHOLESALE_CLUBS'; // Wholesale Clubs
	const CATEGORY_WHOLESALE_FLORIST_SUPPLIERS = 'WHOLESALE_FLORIST_SUPPLIERS'; // Wholesale Florist Suppliers
	const CATEGORY_WHOLESALE_PRESCRIPTION_DRUGS = 'WHOLESALE_PRESCRIPTION_DRUGS'; // Wholesale Prescription Drugs
	const CATEGORY_WILDLIFE_PRODUCTS = 'WILDLIFE_PRODUCTS'; // Wildlife Products
	const CATEGORY_WIRE_TRANSFER = 'WIRE_TRANSFER'; // Wire Transfer
	const CATEGORY_WIRE_TRANSFER_AND_MONEY_ORDER = 'WIRE_TRANSFER_AND_MONEY_ORDER'; // Wire transfer and money order
	const CATEGORY_WOMEN_ACCESSORY_SPECIALITY = 'WOMEN_ACCESSORY_SPECIALITY'; // Women's Accessory/Speciality
	const CATEGORY_WOMEN_CLOTHING = 'WOMEN_CLOTHING'; // Women's clothing

	public static function all($params, $apiContext = null, $restCall = null)
	{
		ArgumentValidator::validate($params, 'params');
		$payLoad = '';
		$allowedParams = [
			'page_size'               => 1,
			'page'                    => 1,
			'total_required'          => true,
		];

		$json = self::executeCall(
			'/v1/catalogs/products?' . http_build_query(array_intersect_key($params, $allowedParams)),
			'GET',
			$payLoad,
			null,
			$apiContext,
			$restCall
		);

		$ret = new CatalogProductsList();
		$ret->fromJson($json);

		return $ret;
	}

	/**
	 * @param string $productId
	 * @param ApiContext|null $apiContext
	 * @param PayPalRestCall|null $restCall
	 * @return CatalogProduct
	 */
	public static function get($productId, $apiContext = null, $restCall = null)
	{
		ArgumentValidator::validate($productId, 'productId');
		$payLoad = '';
		$json = self::executeCall(
			"/v1/catalogs/products/$productId",
			'GET',
			$payLoad,
			null,
			$apiContext,
			$restCall
		);
		$ret = new self();
		$ret->fromJson($json);
		return $ret;
	}

	/**
	 * @param ApiContext|null $apiContext
	 * @param PayPalRestCall|null $restCall
	 * @return CatalogProduct
	 */
	public function create($apiContext = null, $restCall = null)
	{
		$json = self::executeCall(
			'/v1/catalogs/products',
			'POST',
			$this->toJSON(),
			null,
			$apiContext,
			$restCall
		);
		$ret = new self();
		$ret->fromJson($json);
		return $ret;
	}
}
